apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME production endpoint (trusted certs, real rate limits)
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rohanathan.s@hotmail.com          
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: rootsnwings-465610
            hostedZoneName: cloudsofglasgow
